# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.
main:
  - name: About
    url: /about/
    weight: 20
  - name: Members
    weight: 30

  - name: Professor
    parent: Members
    url: /professor/
    weight: 10
  - name: Alumni
    parent: Members
    url: /alumni/
    weight: 20
  - name: Students
    parent: Members
    url: /students/
    weight: 30

  - name: Research
    weight: 40

  - name: introduction
    parent: Research
    url: /research/
    weight: 10
  - name: Publications
    parent: Research
    url: /publications/
    weight: 20

  - name: Contact Us
    url: /contact/
    weight: 50



